services:
  postgres:
    image: postgres:16-alpine
    container_name: fkingduel_postgres
    restart: unless-stopped
    networks: 
      - fkingduel
    environment:
      POSTGRES_DB: fkingdueldb
      POSTGRES_USER: fkingdueluser
      POSTGRES_PASSWORD: fkingduelpassword
    ports:
      - "5432:5432"
    volumes:
      - ./backend/.data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fkingduel_redis
    restart: unless-stopped
    networks:
      - fkingduel
    ports:
      - "6379:6379"
    volumes:
      - ./backend/.redis:/data

networks:
  fkingduel:
    driver: bridge
