services:
  postgres:
    image: postgres:18-alpine
    container_name: fduel_postgres
    restart: unless-stopped
    networks: 
      - fduel
    environment:
      POSTGRES_DB: ${FDUEL_POSTGRES_DB}
      POSTGRES_USER: ${FDUEL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FDUEL_POSTGRES_PASSWORD}
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/.data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    container_name: fduel_redis
    restart: unless-stopped
    networks:
      - fduel
    ports:
      - "6379:6379"
    volumes:
      - ./backend/.redis:/data

  jaeger:
    image: jaegertracing/jaeger:2.20.0
    container_name: fduel_jaeger
    restart: no
    networks:
      - fduel
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"

  fduel:
    build: ./backend
    container_name: fduel_backend
    restart: no
    networks:
      - fduel
    env_file:
      - .env.docker
    environment:
      - FDUEL_MIGRATE=true
      - OTEL_SERVICE_NAME=fduel-web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: opentelemetry-instrument daphne -b 0.0.0.0 -p 8000 core.asgi:application

  celery_worker:
    build: ./backend
    container_name: fduel_celery_worker
    restart: no
    networks:
      - fduel
    environment:
      - OTEL_SERVICE_NAME=fduel-worker
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
    command: opentelemetry-instrument celery -A core.celery worker --loglevel=info

  celery_beat:
    build: ./backend
    container_name: fduel_celery_beat
    restart: no
    networks:
      - fduel
    environment:
      - OTEL_SERVICE_NAME=fduel-beat
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
    command: opentelemetry-instrument celery -A core.celery beat --loglevel=info

networks:
  fduel:
    driver: bridge
