# Generated by Django 6.1 on 2026-08-22 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemPower', models.IntegerField(default=0)),
                ('itemWeight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worldName', models.CharField(max_length=100)),
                ('worldTotalCreatures', models.IntegerField(default=100)),
                ('worldMinLevel', models.IntegerField(default=1)),
                ('worldMaxLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorldCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatureName', models.CharField(max_length=100)),
                ('creatureLevel', models.IntegerField(default=1)),
                ('creatureLife', models.IntegerField(default=100)),
                ('creatureChanceDrop', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100)),
                ('playerLevel', models.IntegerField(default=1)),
                ('playerExp', models.IntegerField(default=0)),
                ('playerPower', models.IntegerField(default=1)),
                ('playerStamina', models.IntegerField(default=100)),
                ('playerStatus', models.CharField(default='idle', max_length=50)),
                ('playerMaxWeight', models.IntegerField(default=100)),
                ('playerCurrency', models.IntegerField(default=0)),
                ('playerEquipedArmour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_armour_equipped', to='mmo.item')),
                ('playerEquipedWeapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_weapon_equipped', to='mmo.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.player')),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.player')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.worldcreature')),
            ],
        ),
    ]
