# Generated by Django 6.1 on 2026-08-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_power', models.IntegerField(default=0)),
                ('item_weight', models.IntegerField(default=1)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('consumable', 'Consumable')], max_length=50)),
                ('item_consumable_type', models.CharField(blank=True, choices=[('life', 'Life'), ('stamina', 'Stamina')], max_length=50, null=True)),
                ('item_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_name', models.CharField(max_length=100)),
                ('world_total_creatures', models.IntegerField(default=100)),
                ('world_min_level', models.IntegerField(default=1)),
                ('world_max_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_life', models.IntegerField(default=100)),
                ('player_level', models.IntegerField(default=1)),
                ('player_exp', models.IntegerField(default=0)),
                ('player_power', models.IntegerField(default=10)),
                ('player_stamina', models.IntegerField(default=100)),
                ('player_status', models.CharField(default='idle', max_length=50)),
                ('player_max_weight', models.IntegerField(default=100)),
                ('player_currency', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_equipped_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_armour_equipped', to='mmo.playerinventory'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_equipped_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_weapon_equipped', to='mmo.playerinventory'),
        ),
        migrations.CreateModel(
            name='WorldCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creature_name', models.CharField(max_length=100)),
                ('creature_level', models.IntegerField(default=1)),
                ('creature_life', models.IntegerField(default=100)),
                ('creature_chance_drop', models.IntegerField(default=50)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.world')),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.player')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.worldcreature')),
            ],
        ),
    ]
