# Generated by Django 6.1 on 2026-08-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerLife',
            field=models.IntegerField(default=100),
        ),
    ]
