# Generated by Django 6.1 on 2026-08-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_max_life',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='player_max_stamina',
            field=models.IntegerField(default=100),
        ),
    ]
