# Generated by Django 6.1 on 2026-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('fighting', 'Fighting'), ('dead', 'Dead')], default='idle', max_length=50),
        ),
    ]
