# Generated by Django 6.1 on 2026-08-25 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemCreatedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
