# Generated by Django 6.1 on 2026-08-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0002_player_playerlife'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcreature',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mmo.world'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='playerPower',
            field=models.IntegerField(default=10),
        ),
    ]
