# Generated by Django 6.1 on 2026-08-30 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0002_player_player_max_life_player_player_max_stamina'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='opponent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_fight', to='mmo.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='mmo.world'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='creature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mmo.worldcreature'),
        ),
    ]
