# Generated by Django 6.1 on 2026-08-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0003_worldcreature_world_alter_player_playerpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemConsumableType',
            field=models.CharField(blank=True, choices=[('life', 'Life'), ('stamina', 'Stamina')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('consumable', 'Consumable')], default='weapon', max_length=50),
            preserve_default=False,
        ),
    ]
