# Generated by Django 6.1 on 2026-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0003_fight_opponent_player_player_world_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_last_death_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
