# Generated by Django 6.1 on 2026-09-23 18:11

from django.db import migrations, models

def copy_life_to_max_life(apps, schema_editor):
    WorldCreature = apps.get_model('mmo', 'WorldCreature')
    WorldCreature.objects.update(creature_max_life=models.functions.Greatest(models.F('creature_life'), 100))

class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0004_player_player_last_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcreature',
            name='creature_max_life',
            field=models.IntegerField(default=100),
        ),
        migrations.RunPython(copy_life_to_max_life, migrations.RunPython.noop),
    ]
