# Generated by Django 6.1 on 2026-08-26 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mmo', '0002_alter_player_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_currency_amount', models.IntegerField(default=0)),
                ('market_created_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mmo.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmo.player')),
            ],
        ),
    ]
