# GAME CONSTANTS
LEVEL_MAX=100
PLAYER_TOTAL_STAMINA=100
PLAYER_BASE_STAMINA_USAGE=1
PLAYER_STAMINA_LINEAR_POWER=1.8 #how stamina grows based on power points
PLAYER_STAMINA_TOTAL_POWER_REGEN=0.4 #percent stamina regens at each tick
PLAYER_BASE_LIFE=100
PLAYER_LIFE_LINEAR_POWER=1.5 #how life grows based on power points
PLAYER_LIFE_TOTAL_POWER_REGEN=0.1 #percent life regens at each tick
PLAYER_POWER_ATTACK_VARIATION=0.6
TEMPO_MIN_ATTACK=0.5
TEMPO_MAX_ATTACK=3

LEVELUP_MULTIPLIER_EXP=15
LEVELUP_VARIATION_POWER=1.5
LEVELUP_PLUS_PLAYERPOWER=2.6

MONSTER_MAX_ATTACK=6
MONSTER_MIN_ATTACK=2
MONSTER_POWER_ATTACK_VARIATION=0.4
MONSTER_BASE_LIFE=100
MONSTER_LIFE_VARIATION=3

STAMINA_USAGE_WEIGHT_VARIATION=0.5
STAMINA_USAGE_POWER_VARIATION=0.4

# GAME LOGIC
PLAYER_TIME_DEATH_COOLDOWN=120

# DJANGO CACHE
PLAYER_IS_ATTACKING='player:attacking:{player_id}'
UNLOCK_FIGHT_LOCK='unlock:fight:{fight_id}'