# GAME CONSTANTS
LEVEL_MAX=100
PLAYER_TOTAL_STAMINA=100
PLAYER_BASE_LIFE=100
PLAYER_LIFE_LINEAR_POWER=1.5 #how life grows based on power points
PLAYER_LIFE_TOTAL_POWER_REGEN=0.1 #percent life regens at each tick
PLAYER_POWER_ATTACK_VARIATION=0.6
TEMPO_MIN_ATTACK=0.5
TEMPO_MAX_ATTACK=2

MONSTER_MAX_ATTACK=6
MONSTER_MIN_ATTACK=2
MONSTER_POWER_ATTACK_VARIATION=0.4

# DJANGO CACHE
PLAYER_IS_ATTACKING="player:attacking:{playerId}"